/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your Sui client by calling
 * `getMvrCache("mainnet")` or `getMvrCache("testnet")` and passing it as the `overrides` option.
 */

const mainnetResolution = {
  packages: {},
  types: {},
};
const testnetResolution = {
  packages: {
    "@evefrontier/world-test":
      "0xffe76dbcb155decf4343d6e68b572191024e0a0990eca808888745e1a16f3cba",
    "@evefrontier/world-uat":
      "0x04edab96ec1a8aad7be679eccf128f446e378a3569e9b6a2934df26452d2fccc",
    "@evefrontier/world":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1",
    "@evefrontier/world-dev":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3",
  },
  types: {
    "@evefrontier/world-dev::inventory::ItemMintedEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::inventory::ItemMintedEvent",
    "@evefrontier/world-uat::status::StatusChangedEvent":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::status::StatusChangedEvent",
    "@evefrontier/world-test::access::OwnerCap":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::access::OwnerCap",
    "@evefrontier/world-uat::inventory::ItemBurnedEvent":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::inventory::ItemBurnedEvent",
    "@evefrontier/world-uat::character::Character":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::character::Character",
    "@evefrontier/world::object_registry::ObjectRegistry":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::object_registry::ObjectRegistry",
    "@evefrontier/world::inventory::ItemBurnedEvent":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::inventory::ItemBurnedEvent",
    "@evefrontier/world-test::character::Character":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::character::Character",
    "@evefrontier/world-uat::in_game_id::TenantItemId":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::in_game_id::TenantItemId",
    "@evefrontier/world-test::fuel::FuelConfig":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::fuel::FuelConfig",
    "@evefrontier/world-dev::character::PlayerProfile":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::character::PlayerProfile",
    "@evefrontier/world::in_game_id::TenantItemId":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::in_game_id::TenantItemId",
    "@evefrontier/world-uat::access::OwnerCap":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::access::OwnerCap",
    "@evefrontier/world-uat::fuel::FuelEvent":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::fuel::FuelEvent",
    "@evefrontier/world-dev::object_registry::ObjectRegistry":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::object_registry::ObjectRegistry",
    "@evefrontier/world-dev::character::Character":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::character::Character",
    "@evefrontier/world-dev::status::StatusChangedEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::status::StatusChangedEvent",
    "@evefrontier/world-uat::character::PlayerProfile":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::character::PlayerProfile",
    "@evefrontier/world-uat::fuel::FuelConfig":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::fuel::FuelConfig",
    "@evefrontier/world-dev::energy::EnergyConfig":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::energy::EnergyConfig",
    "@evefrontier/world::status::StatusChangedEvent":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::status::StatusChangedEvent",
    "@evefrontier/world-dev::in_game_id::TenantItemId":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::in_game_id::TenantItemId",
    "@evefrontier/world-dev::fuel::FuelEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::fuel::FuelEvent",
    "@evefrontier/world-test::energy::EnergyConfig":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::energy::EnergyConfig",
    "@evefrontier/world::access::OwnerCap":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::access::OwnerCap",
    "@evefrontier/world-test::inventory::ItemBurnedEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::inventory::ItemBurnedEvent",
    "@evefrontier/world-dev::inventory::ItemBurnedEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::inventory::ItemBurnedEvent",
    "@evefrontier/world::fuel::FuelEvent":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::fuel::FuelEvent",
    "@evefrontier/world-test::character::PlayerProfile":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::character::PlayerProfile",
    "@evefrontier/world-test::in_game_id::TenantItemId":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::in_game_id::TenantItemId",
    "@evefrontier/world-dev::fuel::FuelConfig":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::fuel::FuelConfig",
    "@evefrontier/world::character::Character":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::character::Character",
    "@evefrontier/world-test::object_registry::ObjectRegistry":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::object_registry::ObjectRegistry",
    "@evefrontier/world-dev::access::OwnerCap":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::access::OwnerCap",
    "@evefrontier/world-test::fuel::FuelEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::fuel::FuelEvent",
    "@evefrontier/world::character::PlayerProfile":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::character::PlayerProfile",
    "@evefrontier/world::energy::EnergyConfig":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::energy::EnergyConfig",
    "@evefrontier/world-uat::energy::EnergyConfig":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::energy::EnergyConfig",
    "@evefrontier/world::fuel::FuelConfig":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::fuel::FuelConfig",
    "@evefrontier/world-uat::inventory::ItemMintedEvent":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::inventory::ItemMintedEvent",
    "@evefrontier/world-test::status::StatusChangedEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::status::StatusChangedEvent",
    "@evefrontier/world::inventory::ItemMintedEvent":
      "0x8b8a46ed766fa1358ce7c5c51f6a164b13d627a63e45343f69ed0ba0446c1aa1::inventory::ItemMintedEvent",
    "@evefrontier/world-test::inventory::ItemMintedEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::inventory::ItemMintedEvent",
    "@evefrontier/world-uat::object_registry::ObjectRegistry":
      "0xd12a70c74c1e759445d6f209b01d43d860e97fcf2ef72ccbbd00afd828043f75::object_registry::ObjectRegistry",
  },
};

export function getMvrCache(network: "mainnet" | "testnet") {
  return network === "mainnet" ? mainnetResolution : testnetResolution;
}
