/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your Sui client by calling
 * `getMvrCache("mainnet")` or `getMvrCache("testnet")` and passing it as the `overrides` option.
 */

const mainnetResolution = {
  packages: {},
  types: {},
};
const testnetResolution = {
  packages: {
    "@evefrontier/world-test":
      "0x4adc2ee28cf9ea38c164ac8ae4c2e174f4869c9bbcbd588beb110f4fbe4a2554",
    "@evefrontier/world":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92",
    "@evefrontier/world-uat":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230",
    "@evefrontier/world-dev":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3",
  },
  types: {
    "@evefrontier/world-dev::access::OwnerCap":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::access::OwnerCap",
    "@evefrontier/world::energy::EnergyConfig":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::energy::EnergyConfig",
    "@evefrontier/world-uat::status::StatusChangedEvent":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::status::StatusChangedEvent",
    "@evefrontier/world-dev::status::StatusChangedEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::status::StatusChangedEvent",
    "@evefrontier/world-uat::inventory::ItemBurnedEvent":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::inventory::ItemBurnedEvent",
    "@evefrontier/world-uat::character::PlayerProfile":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::character::PlayerProfile",
    "@evefrontier/world-dev::inventory::ItemBurnedEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::inventory::ItemBurnedEvent",
    "@evefrontier/world::inventory::ItemMintedEvent":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::inventory::ItemMintedEvent",
    "@evefrontier/world-dev::object_registry::ObjectRegistry":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::object_registry::ObjectRegistry",
    "@evefrontier/world-uat::object_registry::ObjectRegistry":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::object_registry::ObjectRegistry",
    "@evefrontier/world::object_registry::ObjectRegistry":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::object_registry::ObjectRegistry",
    "@evefrontier/world-uat::inventory::ItemMintedEvent":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::inventory::ItemMintedEvent",
    "@evefrontier/world-uat::fuel::FuelEvent":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::fuel::FuelEvent",
    "@evefrontier/world-test::inventory::ItemBurnedEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::inventory::ItemBurnedEvent",
    "@evefrontier/world-test::status::StatusChangedEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::status::StatusChangedEvent",
    "@evefrontier/world::fuel::FuelEvent":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::fuel::FuelEvent",
    "@evefrontier/world-dev::character::Character":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::character::Character",
    "@evefrontier/world-test::object_registry::ObjectRegistry":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::object_registry::ObjectRegistry",
    "@evefrontier/world-test::access::OwnerCap":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::access::OwnerCap",
    "@evefrontier/world-dev::energy::EnergyConfig":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::energy::EnergyConfig",
    "@evefrontier/world::inventory::ItemBurnedEvent":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::inventory::ItemBurnedEvent",
    "@evefrontier/world::in_game_id::TenantItemId":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::in_game_id::TenantItemId",
    "@evefrontier/world::status::StatusChangedEvent":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::status::StatusChangedEvent",
    "@evefrontier/world-dev::fuel::FuelEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::fuel::FuelEvent",
    "@evefrontier/world-dev::in_game_id::TenantItemId":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::in_game_id::TenantItemId",
    "@evefrontier/world-test::inventory::ItemMintedEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::inventory::ItemMintedEvent",
    "@evefrontier/world::character::PlayerProfile":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::character::PlayerProfile",
    "@evefrontier/world-uat::access::OwnerCap":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::access::OwnerCap",
    "@evefrontier/world-uat::fuel::FuelConfig":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::fuel::FuelConfig",
    "@evefrontier/world-test::energy::EnergyConfig":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::energy::EnergyConfig",
    "@evefrontier/world-test::in_game_id::TenantItemId":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::in_game_id::TenantItemId",
    "@evefrontier/world-test::fuel::FuelConfig":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::fuel::FuelConfig",
    "@evefrontier/world::access::OwnerCap":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::access::OwnerCap",
    "@evefrontier/world-test::character::PlayerProfile":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::character::PlayerProfile",
    "@evefrontier/world-dev::inventory::ItemMintedEvent":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::inventory::ItemMintedEvent",
    "@evefrontier/world-test::fuel::FuelEvent":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::fuel::FuelEvent",
    "@evefrontier/world-dev::fuel::FuelConfig":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::fuel::FuelConfig",
    "@evefrontier/world::fuel::FuelConfig":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::fuel::FuelConfig",
    "@evefrontier/world-dev::character::PlayerProfile":
      "0xc7cf7d22a2875dba899d5410d61600c15477d82d1cf132133f522271f205a4e3::character::PlayerProfile",
    "@evefrontier/world-uat::energy::EnergyConfig":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::energy::EnergyConfig",
    "@evefrontier/world::character::Character":
      "0x7be18d6294e533bedd9a5d70a96ce8d9d4b87a7c74188ba65d3fe966bbed9d92::character::Character",
    "@evefrontier/world-uat::in_game_id::TenantItemId":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::in_game_id::TenantItemId",
    "@evefrontier/world-uat::character::Character":
      "0x28eab6a6e9e12808a15901b12fcd3adfb07317d716dcaeb3f2965e25c7da0230::character::Character",
    "@evefrontier/world-test::character::Character":
      "0x353988e063b4683580e3603dbe9e91fefd8f6a06263a646d43fd3a2f3ef6b8c1::character::Character",
  },
};

export function getMvrCache(network: "mainnet" | "testnet") {
  return network === "mainnet" ? mainnetResolution : testnetResolution;
}
