#!/usr/bin/env sh
set -e
ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

bun audit --audit-level=critical
bunx nx run-many -t lint --verbose --nxBail=true
bun --filter @evefrontier/dapp-kit test:run
