name: Build

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'nx.json'
      - 'tsconfig.json'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm nx run-many -t build --verbose --nxBail=true
          pnpm nx run assembly:ci:build --verbose --nxBail=true
        env:
          CI: true
